/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../src/encoder.v:1" *)
module priority_encoder(clk, D, O);
  (* src = "../src/encoder.v:6" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "../src/encoder.v:2" *)
  input [7:0] D;
  (* src = "../src/encoder.v:4" *)
  output [3:0] O;
  (* src = "../src/encoder.v:3" *)
  input clk;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(D[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2b_1 _09_ (
    .A_N(D[2]),
    .B(D[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a21oi_1 _10_ (
    .A1(_01_),
    .A2(_02_),
    .B1(D[4]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _11_ (
    .A(D[5]),
    .B(_03_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__o21bai_1 _12_ (
    .A1(D[6]),
    .A2(_04_),
    .B1_N(D[7]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__nor2_1 _13_ (
    .A(D[4]),
    .B(D[5]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21ai_0 _14_ (
    .A1(D[3]),
    .A2(D[2]),
    .B1(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(D[7]),
    .B(D[6]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _16_ (
    .A(_06_),
    .B(_07_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__nand2_1 _17_ (
    .A(_05_),
    .B(_07_),
    .Y(_00_[2])
  );
  (* src = "../src/encoder.v:6" *)
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(O[0])
  );
  (* src = "../src/encoder.v:6" *)
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(O[1])
  );
  (* src = "../src/encoder.v:6" *)
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(O[2])
  );
  assign _00_[3] = 1'h0;
  assign O[3] = 1'h0;
endmodule
